# Generated by Django 5.0.2 on 2024-03-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutter_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo_Item',
            new_name='TodoItem',
        ),
    ]
